 Regularization in ML

REgularization is one of the most important concepts of ML. It is a technique to prevent the model from overfitting and underfitting by adding extra information to it.

Sometimes the ML model performs well with the training data but does not perform well with the test data. It means the model is not able to predict the output when deals with unseen data.The problem can be deal with the help of of a regularization technique.

There are 2 terms to define the problem

1)Underfitting

Underfitting is when our model is not able to learn the basic pattern of our dataset. In the case of underfitting model is unable to perform well even on the training data hence we cannot expect it to perform well on the testing data. This is the case when we are suppossed to increase the complexity of the model or add more features to the dataset.

2)Overfitting

Overfitting is phenomenon that occurs when a ML model is able to perform well on training but does not perform well on testing data. This happens when our model memorize the training data instead of the pattern on it.

BIAS

Bias refers to the errors which occurs when we try to fit a statiscal model on real world data which does not fit perfectly well on some mathematical model. High Bias refers to the case when the model is unable to learn the pattern in the data at hand and hence perform poorly. It is mostly under Underfit model

VARIANCE

Variance implies the error value that occurs when we try to make predictions by using data that is not previously seen by model. There is a situation known as high variance that occurs when model is able to perform well on training but does not perform well on testing data.
 How to identify the underfit and overfit?

In underfit MSE high and rscore is low in training===Low features

In overfit MSE 0 and r2score is 0.99 is training but in testing MSE becomes high i.e is overfit situation

How to solve this

Overfit and Underfit solution MSE+ERROR

2 techniques

L1 LASSO
L2 Ridge
Overfit====Remove Features Underfit===Add Features

LASSO=== will minimize the coefficient of the unwanted features to 0. RIDGE===Will minimize the coeefficient of the unwanted features

1)Lasso ====∑(y-ŷ)**2/N + α|M|

Ridge ===∑(y-ŷ)*2/N + α|M|*2
standard value of lambda for regularization is between 0 to 0.1# regularzatioj

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
import warnings 
warnings.filterwarnings("ignore")

In [2]:
auto=pd.read_csv("Automobile_data.csv")
auto

symboling normalized-losses         make fuel-type   body-style  \
0            3                 ?  alfa-romero       gas  convertible   
1            3                 ?  alfa-romero       gas  convertible   
2            1                 ?  alfa-romero       gas    hatchback   
3            2               164         audi       gas        sedan   
4            2               164         audi       gas        sedan   
..         ...               ...          ...       ...          ...   
200         -1                95        volvo       gas        sedan   
201         -1                95        volvo       gas        sedan   
202         -1                95        volvo       gas        sedan   
203         -1                95        volvo    diesel        sedan   
204         -1                95        volvo       gas        sedan   

    drive-wheels engine-location  width  height engine-type  engine-size  \
0            rwd           front   64.1    48.8        dohc          130   
1            rwd           front   64.1    48.8        dohc          130   
2            rwd           front   65.5    52.4        ohcv          152   
3            fwd           front   66.2    54.3         ohc          109   
4            4wd           front   66.4    54.3         ohc          136   
..           ...             ...    ...     ...         ...          ...   
200          rwd           front   68.9    55.5         ohc          141   
201          rwd           front   68.8    55.5         ohc          141   
202          rwd           front   68.9    55.5        ohcv          173   
203          rwd           front   68.9    55.5         ohc          145   
204          rwd           front   68.9    55.5         ohc          141   

    horsepower  city-mpg  highway-mpg  price  
0          111        21           27  13495  
1          111        21           27  16500  
2          154        19           26  16500  
3          102        24           30  13950  
4          115        18           22  17450  
..         ...       ...          ...    ...  
200        114        23           28  16845  
201        160        19           25  19045  
202        134        18           23  21485  
203        106        26           27  22470  
204        114        19           25  22625  

[205 rows x 15 columns]

In [3]:
for col in auto:
    print(auto[col].unique())
    print(col)

[ 3  1  2  0 -1 -2]
symboling
['?' '164' '158' '192' '188' '121' '98' '81' '118' '148' '110' '145' '137'
 '101' '78' '106' '85' '107' '104' '113' '150' '129' '115' '93' '142'
 '161' '153' '125' '128' '122' '103' '168' '108' '194' '231' '119' '154'
 '74' '186' '83' '102' '89' '87' '77' '91' '134' '65' '197' '90' '94'
 '256' '95']
normalized-losses
['alfa-romero' 'audi' 'bmw' 'chevrolet' 'dodge' 'honda' 'isuzu' 'jaguar'
 'mazda' 'mercedes-benz' 'mercury' 'mitsubishi' 'nissan' 'peugot'
 'plymouth' 'porsche' 'renault' 'saab' 'subaru' 'toyota' 'volkswagen'
 'volvo']
make
['gas' 'diesel']
fuel-type
['convertible' 'hatchback' 'sedan' 'wagon' 'hardtop']
body-style
['rwd' 'fwd' '4wd']
drive-wheels
['front' 'rear']
engine-location
[64.1 65.5 66.2 66.4 66.3 71.4 67.9 64.8 66.9 70.9 60.3 63.6 63.8 64.6
 63.9 64.  65.2 62.5 66.  61.8 69.6 70.6 64.2 65.7 66.5 66.1 70.3 71.7
 70.5 72.  68.  64.4 65.4 68.4 68.3 65.  72.3 66.6 63.4 65.6 67.7 67.2
 68.9 68.8]
width
[48.8 52.4 54.3 53.1 55.7 55.9 52.  53

In [4]:
auto["normalized-losses"].replace("?",np.nan,inplace=True)
auto["horsepower"].replace("?",np.nan,inplace=True)

In [5]:
auto

symboling normalized-losses         make fuel-type   body-style  \
0            3               NaN  alfa-romero       gas  convertible   
1            3               NaN  alfa-romero       gas  convertible   
2            1               NaN  alfa-romero       gas    hatchback   
3            2               164         audi       gas        sedan   
4            2               164         audi       gas        sedan   
..         ...               ...          ...       ...          ...   
200         -1                95        volvo       gas        sedan   
201         -1                95        volvo       gas        sedan   
202         -1                95        volvo       gas        sedan   
203         -1                95        volvo    diesel        sedan   
204         -1                95        volvo       gas        sedan   

    drive-wheels engine-location  width  height engine-type  engine-size  \
0            rwd           front   64.1    48.8        dohc          130   
1            rwd           front   64.1    48.8        dohc          130   
2            rwd           front   65.5    52.4        ohcv          152   
3            fwd           front   66.2    54.3         ohc          109   
4            4wd           front   66.4    54.3         ohc          136   
..           ...             ...    ...     ...         ...          ...   
200          rwd           front   68.9    55.5         ohc          141   
201          rwd           front   68.8    55.5         ohc          141   
202          rwd           front   68.9    55.5        ohcv          173   
203          rwd           front   68.9    55.5         ohc          145   
204          rwd           front   68.9    55.5         ohc          141   

    horsepower  city-mpg  highway-mpg  price  
0          111        21           27  13495  
1          111        21           27  16500  
2          154        19           26  16500  
3          102        24           30  13950  
4          115        18           22  17450  
..         ...       ...          ...    ...  
200        114        23           28  16845  
201        160        19           25  19045  
202        134        18           23  21485  
203        106        26           27  22470  
204        114        19           25  22625  

[205 rows x 15 columns]

In [6]:
auto["normalized-losses"]=auto["normalized-losses"].astype("float64")
auto["horsepower"]=auto["horsepower"].astype("float64")

In [7]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  164 non-null    float64
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   body-style         205 non-null    object 
 5   drive-wheels       205 non-null    object 
 6   engine-location    205 non-null    object 
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object 
 10  engine-size        205 non-null    int64  
 11  horsepower         203 non-null    float64
 12  city-mpg           205 non-null    int64  
 13  highway-mpg        205 non-null    int64  
 14  price              205 non-null    int64  
dtypes: float64(4), int64(5), object(6)
memory usage: 24.2+ KB


In [8]:
auto.describe()

symboling  normalized-losses       width      height  engine-size  \
count  205.000000         164.000000  205.000000  205.000000   205.000000   
mean     0.834146         122.000000   65.907805   53.724878   126.907317   
std      1.245307          35.442168    2.145204    2.443522    41.642693   
min     -2.000000          65.000000   60.300000   47.800000    61.000000   
25%      0.000000          94.000000   64.100000   52.000000    97.000000   
50%      1.000000         115.000000   65.500000   54.100000   120.000000   
75%      2.000000         150.000000   66.900000   55.500000   141.000000   
max      3.000000         256.000000   72.300000   59.800000   326.000000   

       horsepower    city-mpg  highway-mpg         price  
count  203.000000  205.000000   205.000000    205.000000  
mean   104.256158   25.219512    30.751220  13227.478049  
std     39.714369    6.542142     6.886443   7902.651615  
min     48.000000   13.000000    16.000000   5118.000000  
25%     70.000000   19.000000    25.000000   7788.000000  
50%     95.000000   24.000000    30.000000  10345.000000  
75%    116.000000   30.000000    34.000000  16500.000000  
max    288.000000   49.000000    54.000000  45400.000000

In [9]:
auto["normalized-losses"].fillna(122,inplace=True)
auto["horsepower"].fillna(104,inplace=True)

In [10]:
auto

symboling  normalized-losses         make fuel-type   body-style  \
0            3              122.0  alfa-romero       gas  convertible   
1            3              122.0  alfa-romero       gas  convertible   
2            1              122.0  alfa-romero       gas    hatchback   
3            2              164.0         audi       gas        sedan   
4            2              164.0         audi       gas        sedan   
..         ...                ...          ...       ...          ...   
200         -1               95.0        volvo       gas        sedan   
201         -1               95.0        volvo       gas        sedan   
202         -1               95.0        volvo       gas        sedan   
203         -1               95.0        volvo    diesel        sedan   
204         -1               95.0        volvo       gas        sedan   

    drive-wheels engine-location  width  height engine-type  engine-size  \
0            rwd           front   64.1    48.8        dohc          130   
1            rwd           front   64.1    48.8        dohc          130   
2            rwd           front   65.5    52.4        ohcv          152   
3            fwd           front   66.2    54.3         ohc          109   
4            4wd           front   66.4    54.3         ohc          136   
..           ...             ...    ...     ...         ...          ...   
200          rwd           front   68.9    55.5         ohc          141   
201          rwd           front   68.8    55.5         ohc          141   
202          rwd           front   68.9    55.5        ohcv          173   
203          rwd           front   68.9    55.5         ohc          145   
204          rwd           front   68.9    55.5         ohc          141   

     horsepower  city-mpg  highway-mpg  price  
0         111.0        21           27  13495  
1         111.0        21           27  16500  
2         154.0        19           26  16500  
3         102.0        24           30  13950  
4         115.0        18           22  17450  
..          ...       ...          ...    ...  
200       114.0        23           28  16845  
201       160.0        19           25  19045  
202       134.0        18           23  21485  
203       106.0        26           27  22470  
204       114.0        19           25  22625  

[205 rows x 15 columns]

In [11]:
auto_cate=auto.select_dtypes(["object"])

In [12]:
auto_num=auto.select_dtypes(["float64","int64"])

In [13]:
auto_cate

make fuel-type   body-style drive-wheels engine-location  \
0    alfa-romero       gas  convertible          rwd           front   
1    alfa-romero       gas  convertible          rwd           front   
2    alfa-romero       gas    hatchback          rwd           front   
3           audi       gas        sedan          fwd           front   
4           audi       gas        sedan          4wd           front   
..           ...       ...          ...          ...             ...   
200        volvo       gas        sedan          rwd           front   
201        volvo       gas        sedan          rwd           front   
202        volvo       gas        sedan          rwd           front   
203        volvo    diesel        sedan          rwd           front   
204        volvo       gas        sedan          rwd           front   

    engine-type  
0          dohc  
1          dohc  
2          ohcv  
3           ohc  
4           ohc  
..          ...  
200         ohc  
201         ohc  
202        ohcv  
203         ohc  
204         ohc  

[205 rows x 6 columns]

In [14]:
auto_num

symboling  normalized-losses  width  height  engine-size  horsepower  \
0            3              122.0   64.1    48.8          130       111.0   
1            3              122.0   64.1    48.8          130       111.0   
2            1              122.0   65.5    52.4          152       154.0   
3            2              164.0   66.2    54.3          109       102.0   
4            2              164.0   66.4    54.3          136       115.0   
..         ...                ...    ...     ...          ...         ...   
200         -1               95.0   68.9    55.5          141       114.0   
201         -1               95.0   68.8    55.5          141       160.0   
202         -1               95.0   68.9    55.5          173       134.0   
203         -1               95.0   68.9    55.5          145       106.0   
204         -1               95.0   68.9    55.5          141       114.0   

     city-mpg  highway-mpg  price  
0          21           27  13495  
1          21           27  16500  
2          19           26  16500  
3          24           30  13950  
4          18           22  17450  
..        ...          ...    ...  
200        23           28  16845  
201        19           25  19045  
202        18           23  21485  
203        26           27  22470  
204        19           25  22625  

[205 rows x 9 columns]

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le=LabelEncoder()

for col in auto_cate:
    auto_cate[col]=le.fit_transform(auto_cate[col])
    


In [17]:
auto_cate

make  fuel-type  body-style  drive-wheels  engine-location  engine-type
0       0          1           0             2                0            0
1       0          1           0             2                0            0
2       0          1           2             2                0            5
3       1          1           3             1                0            3
4       1          1           3             0                0            3
..    ...        ...         ...           ...              ...          ...
200    21          1           3             2                0            3
201    21          1           3             2                0            3
202    21          1           3             2                0            5
203    21          0           3             2                0            3
204    21          1           3             2                0            3

[205 rows x 6 columns]

In [18]:
auto2=pd.concat([auto_cate,auto_num],axis=1)
auto2

make  fuel-type  body-style  drive-wheels  engine-location  engine-type  \
0       0          1           0             2                0            0   
1       0          1           0             2                0            0   
2       0          1           2             2                0            5   
3       1          1           3             1                0            3   
4       1          1           3             0                0            3   
..    ...        ...         ...           ...              ...          ...   
200    21          1           3             2                0            3   
201    21          1           3             2                0            3   
202    21          1           3             2                0            5   
203    21          0           3             2                0            3   
204    21          1           3             2                0            3   

     symboling  normalized-losses  width  height  engine-size  horsepower  \
0            3              122.0   64.1    48.8          130       111.0   
1            3              122.0   64.1    48.8          130       111.0   
2            1              122.0   65.5    52.4          152       154.0   
3            2              164.0   66.2    54.3          109       102.0   
4            2              164.0   66.4    54.3          136       115.0   
..         ...                ...    ...     ...          ...         ...   
200         -1               95.0   68.9    55.5          141       114.0   
201         -1               95.0   68.8    55.5          141       160.0   
202         -1               95.0   68.9    55.5          173       134.0   
203         -1               95.0   68.9    55.5          145       106.0   
204         -1               95.0   68.9    55.5          141       114.0   

     city-mpg  highway-mpg  price  
0          21           27  13495  
1          21           27  16500  
2          19           26  16500  
3          24           30  13950  
4          18           22  17450  
..        ...          ...    ...  
200        23           28  16845  
201        19           25  19045  
202        18           23  21485  
203        26           27  22470  
204        19           25  22625  

[205 rows x 15 columns]

In [19]:
x=auto2.drop("price",axis=1) # ALL FEATURS IN X

In [20]:
y=auto2["price"]     # TARGET IN Y

In [21]:
x

make  fuel-type  body-style  drive-wheels  engine-location  engine-type  \
0       0          1           0             2                0            0   
1       0          1           0             2                0            0   
2       0          1           2             2                0            5   
3       1          1           3             1                0            3   
4       1          1           3             0                0            3   
..    ...        ...         ...           ...              ...          ...   
200    21          1           3             2                0            3   
201    21          1           3             2                0            3   
202    21          1           3             2                0            5   
203    21          0           3             2                0            3   
204    21          1           3             2                0            3   

     symboling  normalized-losses  width  height  engine-size  horsepower  \
0            3              122.0   64.1    48.8          130       111.0   
1            3              122.0   64.1    48.8          130       111.0   
2            1              122.0   65.5    52.4          152       154.0   
3            2              164.0   66.2    54.3          109       102.0   
4            2              164.0   66.4    54.3          136       115.0   
..         ...                ...    ...     ...          ...         ...   
200         -1               95.0   68.9    55.5          141       114.0   
201         -1               95.0   68.8    55.5          141       160.0   
202         -1               95.0   68.9    55.5          173       134.0   
203         -1               95.0   68.9    55.5          145       106.0   
204         -1               95.0   68.9    55.5          141       114.0   

     city-mpg  highway-mpg  
0          21           27  
1          21           27  
2          19           26  
3          24           30  
4          18           22  
..        ...          ...  
200        23           28  
201        19           25  
202        18           23  
203        26           27  
204        19           25  

[205 rows x 14 columns]

In [22]:
y

0      13495
1      16500
2      16500
3      13950
4      17450
       ...  
200    16845
201    19045
202    21485
203    22470
204    22625
Name: price, Length: 205, dtype: int64

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [24]:
x_train

make  fuel-type  body-style  drive-wheels  engine-location  engine-type  \
124    14          1           2             2                0            3   
181    19          1           4             2                0            0   
154    19          1           4             0                0            3   
53      8          1           3             1                0            3   
94     12          1           3             1                0            3   
..    ...        ...         ...           ...              ...          ...   
133    17          1           3             1                0            3   
137    17          1           3             1                0            0   
72      9          1           0             2                0            5   
140    18          1           2             0                0            4   
37      5          1           2             1                0            3   

     symboling  normalized-losses  width  height  engine-size  horsepower  \
124          3              122.0   66.3    50.2          156       145.0   
181         -1              122.0   66.5    54.1          161       156.0   
154          0               81.0   63.6    59.1           92        62.0   
53           1              113.0   64.2    54.1           91        68.0   
94           1              128.0   63.8    54.5           97        69.0   
..         ...                ...    ...     ...          ...         ...   
133          2              104.0   66.5    56.1          121       110.0   
137          2              104.0   66.5    56.1          121       160.0   
72           3              142.0   70.5    50.8          234       155.0   
140          2               83.0   63.8    55.7          108        73.0   
37           0              106.0   65.2    53.3          110        86.0   

     city-mpg  highway-mpg  
124        19           24  
181        19           24  
154        27           32  
53         31           38  
94         31           37  
..        ...          ...  
133        21           28  
137        19           26  
72         16           18  
140        26           31  
37         27           33  

[143 rows x 14 columns]

In [25]:
x_test

make  fuel-type  body-style  drive-wheels  engine-location  engine-type  \
78     11          1           2             1                0            3   
97     12          1           4             1                0            3   
151    19          1           2             1                0            3   
44      6          1           3             1                0            3   
40      5          1           3             1                0            3   
..    ...        ...         ...           ...              ...          ...   
39      5          1           3             1                0            3   
110    13          0           4             2                0            2   
164    19          1           2             2                0            3   
56      8          1           2             2                0            6   
176    19          1           3             1                0            3   

     symboling  normalized-losses  width  height  engine-size  horsepower  \
78           2              161.0   64.4    50.8           92        68.0   
97           1              103.0   63.8    53.5           97        69.0   
151          1               87.0   63.6    54.5           92        62.0   
44           1              122.0   63.6    52.0           90        70.0   
40           0               85.0   62.5    54.1          110        86.0   
..         ...                ...    ...     ...          ...         ...   
39           0               85.0   65.2    54.1          110        86.0   
110          0              122.0   68.4    58.7          152        95.0   
164          1              168.0   64.0    52.6           98        70.0   
56           3              150.0   65.7    49.6           70       101.0   
176         -1               65.0   66.5    54.9          122        92.0   

     city-mpg  highway-mpg  
78         31           38  
97         31           37  
151        31           38  
44         38           43  
40         27           33  
..        ...          ...  
39         27           33  
110        25           25  
164        29           34  
56         17           23  
176        27           32  

[62 rows x 14 columns]

In [26]:
lr=LinearRegression()


lr.fit(x_train,y_train)

LinearRegression()

In [27]:
y_pred=lr.predict(x_train)
y_pred

array([16288.78089907, 15862.95149012,  5838.85225599,  7399.90019178,
        7448.21287589,  8340.19293437, 20112.98005262, 12044.05266806,
       10881.60200688, 29477.54680554, 15851.9576196 ,  5979.02408373,
       15128.40723229, 30633.48117389,  8026.17576096, 15238.00805431,
       22671.61292865,  7399.90019178,  6876.94807402,  5437.9556886 ,
        7448.21287589, 13729.614748  , 12275.26312398, 18782.75001558,
       34471.24861641, 19788.70481388, 16081.44896613,  6000.87989708,
       10695.97649555,  9851.0277694 ,  9007.88175727, 15773.38145604,
       18782.75001558, 15020.478675  , 17614.12396185,  8686.88081574,
        6484.6612469 , 19763.98462653, 10389.77691781,  8196.42991173,
       13575.80397841,  9258.49510772, 19763.98462653,  6848.33965708,
       20937.2084722 ,  5364.90343873, 14826.45121096, 18111.27200303,
        7364.42547833,  7448.21287589,  8643.97737049, 18407.97834397,
       27392.95983622, 10345.55762394,  5854.17491501, 20831.03092752,
      

In [28]:
y_pred.shape

(143,)

In [29]:
y_predtest=lr.predict(x_test)
y_predtest

array([ 6147.84196728,  6876.94807402,  5163.80846164,  6529.79192553,
        9097.54846833, 26360.3208709 ,  7459.89768787,   878.21437887,
        5143.88900492, 13519.6257496 , 15450.93058606, 14432.82705309,
       16383.40498746, 11141.23512041, 16456.4588046 , 13899.86889877,
        7470.86479737,  8822.18660532, 10871.94645117,  7575.71466139,
       10982.72029689,  6830.52007514, 13695.70996881,  6367.03291176,
       13729.614748  ,  8822.18660532, 15020.478675  ,  6519.05582477,
        4748.75013887,  9309.72977579,  8168.71319861, 14331.47900196,
       25640.23271405, 11910.76074116, 19763.98462653,  6561.95927003,
        8169.72797695, 30668.72328963,  9815.88325511, 16913.25842105,
        6488.34658028, 20293.80388985,  7703.70101986,  8440.35823684,
        8643.97737049,  7183.2222224 , 40496.49068905,  7556.36394943,
       17202.63501848, 18961.22672644, 26165.63344538, 16952.83948734,
       21835.40214346,  6217.21846787, 13103.59509522,  7263.5879863 ,
      

In [30]:
y_predtest.shape

(62,)

In [31]:

r2_score=r2_score(y_train,y_pred)



print("R2_SCORE:",r2_score)


R2_SCORE: 0.8504568715278973


In [32]:
# train score
lr.score(x_train,y_train)

0.8504568715278973

In [33]:
# test score
lr.score(x_test,y_test)

0.7965544858354378

In [34]:
lr.coef_

array([-2.00105431e+02, -6.22733455e+02, -1.70254151e+02,  1.86861852e+03,
        1.64130546e+04,  2.83207856e+02,  4.51306786e+01,  1.53226590e+00,
        7.89414119e+02,  3.62704004e+02,  9.83648625e+01, -1.08091293e+01,
        3.08067510e+02, -4.17054418e+02])

In [35]:
lr.intercept_

-65023.15888168588

# this situation is overfit

In [36]:
# regularuization

from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

In [37]:
l2=Ridge(0.01)
l2.fit(x_train,y_train)

Ridge(alpha=0.01)

In [38]:
l2.score(x_train,y_train)

0.850455197935917

In [39]:
l2.score(x_test,y_test)

0.796760582814735

In [40]:
l2.coef_

array([-2.00060315e+02, -6.30258245e+02, -1.73610998e+02,  1.86937479e+03,
        1.63207448e+04,  2.85285090e+02,  4.64916534e+01,  1.50273974e+00,
        7.86277229e+02,  3.64199164e+02,  9.83760500e+01, -1.05792338e+01,
        3.07337653e+02, -4.16091219e+02])

In [41]:
# for RIGDE we use for loop

for alpha in range(1,5):
    l2=Ridge(alpha)
    l2.fit(x_train,y_train)
    train_score=l2.score(x_train,y_train)
    test_score=l2.score(x_train,y_train)
    print("Alpha:",alpha)
    print("TRAIN_SCORE:", train_score)
    print("TEST_SCORE:", test_score)
    

Alpha: 1
TRAIN_SCORE: 0.8436017374447923
TEST_SCORE: 0.8436017374447923
Alpha: 2
TRAIN_SCORE: 0.835656844158495
TEST_SCORE: 0.835656844158495
Alpha: 3
TRAIN_SCORE: 0.8295968895778684
TEST_SCORE: 0.8295968895778684
Alpha: 4
TRAIN_SCORE: 0.825005387860624
TEST_SCORE: 0.825005387860624


In [42]:
# lasso method
l3=Lasso(1000)
l3.fit(x_train,y_train)

Lasso(alpha=1000)

In [43]:
l3.score(x_test,y_test)

0.790967315566877

In [44]:
l3.score(x_train,y_train)

0.7571403649693784

In [45]:
l3.coef_

array([-126.41383912,   -0.        ,   -0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    3.96256398,
          0.        ,  276.95414293,  135.3349978 ,   16.01298187,
         -0.        , -113.00543405])

In [46]:
for i in range(200,500,50):
    l3=Lasso(i)
    l3.fit(x_train,y_train)
    train_score=l3.score(x_train,y_train)
    test_score=l3.score(x_train,y_train)
    print("Alpha:",i)
    print("TRAIN_SCORE:", train_score)
    print("TEST_SCORE:", test_score)
    
    

Alpha: 200
TRAIN_SCORE: 0.7987397404506457
TEST_SCORE: 0.7987397404506457
Alpha: 250
TRAIN_SCORE: 0.7813850987245384
TEST_SCORE: 0.7813850987245384
Alpha: 300
TRAIN_SCORE: 0.7770076016091987
TEST_SCORE: 0.7770076016091987
Alpha: 350
TRAIN_SCORE: 0.7718329723406027
TEST_SCORE: 0.7718329723406027
Alpha: 400
TRAIN_SCORE: 0.7658637779134938
TEST_SCORE: 0.7658637779134938
Alpha: 450
TRAIN_SCORE: 0.7629198542295678
TEST_SCORE: 0.7629198542295678


In [47]:
l3.coef_

array([-148.55240108,   -0.        ,   -0.        ,    0.        ,
          0.        ,   11.83425872,    0.        ,    5.50970405,
        157.24997062,  359.22123269,  128.84295705,   17.99553142,
          0.        , -104.41859533])

# FINAL RIDGE MODEL
 we are selecting the values from alpha were there is no large different two number like train and test data number 
 
 so we use ALPHA 2 for final model of RIDGE METHOD
 

In [48]:
l2=Ridge(alpha=2)
l2.fit(x_train,y_train)
print(l2.score(x_test,y_test))

0.811034506445969


In [49]:
l2.coef_

array([-1.94640409e+02, -1.13899099e+03, -4.80930429e+02,  1.88116260e+03,
        7.76063665e+03,  4.65935098e+02,  1.66481207e+02, -8.84441662e-01,
        5.06205088e+02,  5.02070049e+02,  1.00152739e+02,  1.04161416e+01,
        2.44076856e+02, -3.27705725e+02])

# FINAL LASSO MODEL

In [50]:
l3=Lasso(alpha=200)
l3.fit(x_train,y_train)
print(l3.score(x_test,y_test))

0.8139303033598891


# CROSS VALIDATION

In [51]:
from sklearn.model_selection import cross_val_score

In [52]:
l2_cross=cross_val_score(l2,x,y,cv=4)
l2_cross

array([0.71178047, 0.86472552, 0.37642252, 0.47023102])

In [53]:
l3_cross=cross_val_score(l3,x,y,cv=4)
l3_cross

array([0.76562095, 0.81869973, 0.43346535, 0.44842141])

In [54]:
np.mean(l2_cross)

0.6057898826480446

In [55]:
np.mean(l3_cross)

0.6165518601597859